# Generated by Django 2.2.7 on 2021-01-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassis',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
