# Generated by Django 2.2.7 on 2021-01-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0003_auto_20210124_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='chassis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miniatures.Chassis'),
            preserve_default=False,
        ),
    ]
