# Generated by Django 2.2.7 on 2021-01-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniatures', '0005_remove_variant_workflow_brought_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='debut_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='threat_value',
            field=models.IntegerField(null=True),
        ),
    ]
