# Generated by Django 2.2.7 on 2021-01-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('melee_capable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('penetration', models.IntegerField()),
                ('traits', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.WeaponType')),
            ],
        ),
    ]
